<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Interpretes</title>
</head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" >
<link rel="stylesheet" href="estilos.css">
<body>
	<form class="formulario3">
		<h1>Intérpretes</h1>
	¿Qué es un intérprete?
	<br>
	Un intérprete es un programa informático que procesa el código fuente de un proyecto de software durante su tiempo de ejecución, es decir, mientras el software se está ejecutando, y actúa como una interfaz entre ese proyecto y el procesador. Un intérprete siempre procesa el código línea por línea, de modo que lee, analiza y prepara cada secuencia de forma consecutiva para el procesador.
	<br>
	Los principales IDES que utilizan un intérprete son:
	<ol type="I">
		<li>Visual Studio</li>
		<li>Spyder(Anaconda3)</li>
		<li>SharpDevelop</li>
	</ol>
	Planteamiento del problema:
	<br>
	Hacer una simulación de una heladería.
	<label>Código fuente: </label>
	<textarea rows="10" cols="100" readonly>
package heladeria12;

import javax.swing.JOptionPane;

/**
 *
 * @author pepek
 */
public class HeladeriaMortagus extends javax.swing.JFrame {

    double cambio, recibo;
    double total = 0;
    /**
     * Creates new form HeladeriaMortagus
     */
    public HeladeriaMortagus() {
        initComponents();
        lblHelado2.setVisible(false);
        cmbSabor2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGpHelado = new javax.swing.ButtonGroup();
        btnPagar = new javax.swing.JButton();
        lblHelado1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        lblHelado3 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        lblTipoHelado = new javax.swing.JLabel();
        lblHelado2 = new javax.swing.JLabel();
        cmbSabor1 = new javax.swing.JComboBox<>();
        rbSencillo = new javax.swing.JRadioButton();
        rbDoble = new javax.swing.JRadioButton();
        lblHelado = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        cmbSabor2 = new javax.swing.JComboBox<>();
        txtCambio1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        lblHelado1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblHelado1.setText("Heladería mortagus\n");
        lblHelado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblHelado3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHelado3.setText("Helado sencillo $30 y helado doble $40");
        lblHelado3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar helado");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total");
        lblTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCambio.setText("Cambio");
        lblCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTipoHelado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTipoHelado.setText("Tipo de helado");
        lblTipoHelado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHelado2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHelado2.setText("Seleccione sabor\n");

        cmbSabor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSabor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Vainilla", "Chispas de chocolate", "Menta", "Cereza", "Café" }));

        btnGpHelado.add(rbSencillo);
        rbSencillo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSencillo.setText("Sencillo");
        rbSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSencilloActionPerformed(evt);
            }
        });

        btnGpHelado.add(rbDoble);
        rbDoble.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbDoble.setText("Doble");
        rbDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDobleActionPerformed(evt);
            }
        });

        lblHelado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHelado.setText("Seleccione sabor");
        lblHelado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCambio.setText("Insertar dinero");

        cmbSabor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSabor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Vainilla", "Chispas de chocolate", "Menta", "Cereza", "Café" }));

        txtCambio1.setEditable(false);
        txtCambio1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblHelado1)
                        .addGap(226, 226, 226))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHelado3)
                                .addGap(156, 156, 156))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoHelado)
                                    .addComponent(lblHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbSencillo)
                                    .addComponent(cmbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotal)
                                    .addComponent(txtCambio1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHelado2)
                                            .addComponent(rbDoble))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregar)
                                            .addComponent(cmbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPagar)
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHelado1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHelado3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSencillo)
                    .addComponent(rbDoble)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSabor1)
                    .addComponent(lblHelado2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSabor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar)
                    .addComponent(txtCambio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>                        

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try{
        recibo = Double.parseDouble(txtCambio.getText());
        btnAgregar.setEnabled(false);
        rbSencillo.setEnabled(false);
        rbDoble.setEnabled(false);
        if (recibo < total){
            total = total - recibo;
            lblCambio.setText("Dinero faltante");
            txtCambio1.setText(Double.toString(total));
        }
        else{
            if (recibo == total){
                total = 0;
                lblCambio.setText("Cambio");
                txtCambio1.setText("Pago exacto, no hay cambio");
                btnPagar.setEnabled(false);
            }
            else {
                cambio = recibo - total;
                lblCambio.setText("Cambio");
                txtCambio1.setText(Double.toString(cambio));
                btnPagar.setEnabled(false);
            }
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error, verifica haber insertado un valor correcto e intenta de nuevo");
        }
    }                                        

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        total = 0;
        lblHelado2.setVisible(false);
        cmbSabor2.setVisible(false);
        btnPagar.setEnabled(true);
        btnAgregar.setEnabled(true);
        txtTotal.setText("");
        txtCambio.setText("Insertar dinero");
        lblCambio.setText("Cambio");
        txtCambio1.setText("");
        rbSencillo.setEnabled(true);
        rbDoble.setEnabled(true);
        btnGpHelado.clearSelection();
    }                                          

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
           System.exit(0);
    }                                         

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if (rbSencillo.isSelected()){
            total = total + 30;
        }
        else {
            if (rbDoble.isSelected()){
                total = total + 40;
            }
            else {
                JOptionPane.showMessageDialog(null, "Seleccione una opción correcta");
            }
        }
        txtTotal.setText(Double.toString(total));
    }                                          

    private void rbDobleActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        if (rbDoble.isSelected()){
            lblHelado2.setVisible(true);
        cmbSabor2.setVisible(true);
        }
    }                                       

    private void rbSencilloActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if(rbSencillo.isSelected()){
            lblHelado2.setVisible(false);
        cmbSabor2.setVisible(false);
        }
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeladeriaMortagus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeladeriaMortagus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeladeriaMortagus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeladeriaMortagus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeladeriaMortagus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup btnGpHelado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cmbSabor1;
    private javax.swing.JComboBox<String> cmbSabor2;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblHelado;
    private javax.swing.JLabel lblHelado1;
    private javax.swing.JLabel lblHelado2;
    private javax.swing.JLabel lblHelado3;
    private javax.swing.JLabel lblTipoHelado;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbDoble;
    private javax.swing.JRadioButton rbSencillo;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCambio1;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration                   
}

	</textarea>
	<img src="imagenes/solucion.png" width="750" height="500" alt="Demo">
	<button type="button" onclick="location.href='index.php'" class="boton">Llévame al index</button>
	<button type="button" onclick="location.href='compiladores.php'" class="boton">Llévame a los compiladores</button>
	<button type="button" onclick="location.href='afd.php'" class="boton">Llévame al AFD</button>
	</form>
</body>
</html>